---
swagger: '2.0'
info:
  title: Документация по АДМ Райффайзенбанк
  contact: {
    email: Adm_product@raiffeisen.ru,
    name: Support e-mail
  }
  x-logo:
    url: images/raifflogo.png
    backgroundColor: '#FFFFFF'
    altText: Raiff logo
  description: |

    # Добавление вносителей по реестру
    Автоматизированный выпуск кодов для внесения наличных в АДМ. Отправьте нам список вносителей реестром через банк-клиент – мы выпустим и направим код по электронной почте.
    1.	Заполните <a download='' target='_blank' href='images/registry_final.xlsx'>реестр</a>
    3.	<a download='' target='_blank' href='images/Instruction_RBO_v1.pdf'>Отправьте список через интернет-банк</a>
    4.	В течение одного дня направим коды внесения по электронной почте, которую вы указали в реестре

    ## Формат реестра
      <a download='' target='_blank' href='images/registry_final.xlsx'>xlsx реестр</a>

      Наименование поля | Значение
      --------|------------------
      Наименование Клиента | Полное наименование компании
      Расчетный Счет Организации | Счёт Компании, открытый в Банке, к которому будут созданы коды внесения
      Фамилия | Фамилия сотрудника-вносителя, которому будет создан код
      Имя | Имя сотрудника-вносителя, которому будет создан код
      Отчество | Отчество сотрудника-вносителя, которому будет создан код
      Пол | Пол сотрудника-вносителя, которому создаётся код
      Дата | Дата рождения
      Страна | Страна рождения
      Гражданство | Гражданство вносителя (для граждан других государств выпуск кода осуществляется по скану паспорта)
      Серия | Серия паспорта РФ
      Номер | Номер паспорта РФ
      Когда выдан | Дата выдачи паспорта РФ
      Кем Выдан | Кем выдан паспорт РФ
      Страна | Страна прописки
      Регион | Регион адреса прописки
      Населенный пункт | Населенный пункт адреса прописки
      Улица | Улица адреса прописки
      Дом | Дом адреса прописки
      E-mail | Адрес электронной почты, на который необходимо отправить созданный код (почта вносителя)
