---
swagger: '2.0'
info:
  title: API интеграции выплат
  contact: {
    email: ecom@raiffeisen.ru,
    name: Support e-mail
  }
  x-logo:
    url: images/raifflogo.png
    backgroundColor: '#FFFFFF'
    altText: Raiff logo
  description: |

    Свои предложения и идеи о документации можно оставить в репозитории по адресу: https://github.com/Raiffeisen-DGTL/ecom-API/blob/master/payout.yml

    # Описание API
    Взаимодействие осуществляется по протоколу HTTP с использованием методов GET/POST (в описании каждого запроса явно указан требуемый метод и адрес).

    POST-запросы используют JSON-аргументы, GET-запросы работают со строками запросов.

    API всегда возвращает ответ в формате JSON, независимо от типа запроса.

    Ответ любого метода содержит код сообщения (code). Если в процессе обработки любого запроса произойдет логическая ошибка, API вернет дополнительно описание ошибки (message).

    # Авторизация

     Авторизация производится посредством секретного ключа API (SECRET_KEY). Параметр авторизации указывается в заголовке Authorization, значение которого формируется как "Bearer SECRET_KEY".

     Так же настраивается список IP с которых система будет пропускать запросы.

     Продовый хост: https://e-commerce.raiffeisen.ru

     Тестовый хост: https://test.ecom.raiffeisen.ru

servers:
  - url: https://e-commerce.raiffeisen.ru/api
    description: Production API
  - url: https://test.ecom.raiffeisen.ru/api
    description: Sandbox API
tags:
  - name: api-controller
    x-displayName: 'Работа с выплатами'
    description: |
      Для реализации взаимодействия с партнёром Райффайзенбанк предоставляет API из следующих запросов:
        * получение списка банков, принимающих выплаты по СБП,
        * запрос на проведение выплаты,
        * получение статуса выплаты

      Банки, подключенные к приему выплат по СБП вы сможете посмотреть на сайте https://sbp.nspk.ru/participants/ в разделе "Оплата по QR".

      Мы автоматически поддерживаем актуальный список и возвращаем его для вас в запросе на получение банков частников.

  - name: Callback
    x-displayName: 'Уведомление о выплатах'
    description: |
      Для информирования ТСП о проведенных операциях могут использоваться HTTP-уведомления на адрес, указанный в его настройках.

      Для партнёра уведомление представляет собой входящий POST-запрос, который использует JSON-структуру.

      Уведомление считается принятым, если получатель ответил на запрос кодом HTTP 200.

      Ответы с любыми другими HTTP-кодами будут считаться невалидными.

      Повторные попытки отправки будут проводиться в течение суток с нарастающим интервалом.

      Для проверки подлинности уведомления к данным добавляется подпись в заголовке  X-Api-Signature-SHA256, полученная на основе общего секретного ключа и контрольной строки (amount|id|statusValue|statusDate) с помощью HMAC-SHA-256.

      Уведомления отправляются с IP 193.28.44.23

  - name: Registry
    x-displayName: 'Реестр'
    description: |
      Для подключения отправки реестров необходимо написать на ecom@raiffeisen.ru

      Реестры по операциям отправляются на ежедневной основе.

      В случае отсуствия операций за день, реестр на следующий день не отправляется.

      Формат реестра:

      Наименование колонки | Значение
      --------|------------------
      Мерчант | Идентификатор в системе СБП
      Дата операции МСК | Дата и время проведения операции
      Тип | Тип операции
      id заказа | Id операции в системе партнера (id)
      id возврата |  Не используется
      Комментарий | Комментарий к заказу
      Способ оплаты | Instant Payment QR
      Данные оплаты | PAYOUT
      id клиента | Маскированный код получателя
      Сумма | Сумма транзакции
      Комиссия | Комиссия по транзакции
      Дополнительные поля | Дополнительная информация (Пока не используется)

      <a download='' target='_blank' href='images/SBPPayoutReport.csv'>Пример реестра</a>

  - name: Statement
    x-displayName: 'Выписка'
    description: |
      Выписку может выгрузить в банк-клиенте в разных форматах.

      <a download='' target='_blank' href='images/test_statement_payout.pdf'>Пример выписки</a>

      В назначение платежа есть системиный префикс: номер проводки , тип операции , идентификатор мерчанта НСПК.

      В примерах выписки указаны стандартные назначение платежа, вы можете его изменить, для этого необходимо при выплате передавать параметр paymentDetails с вашими данными, при этом  ваше значение будет идти после системного префикса.


x-tagGroups:
  - name: API
    tags:
      - api-controller
      - Callback
  - name: Сверка
    tags:
      - Registry
      - Statement

paths:
  /payout/v1/sbp/banks/:
    get:
      tags:
        - api-controller
      summary: Получение списка банков, принимающих выплаты по СБП
      operationId: getArrayBanks
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Bearer secret key
          required: true
      responses:
        '200':
          description: Ответ с успешным результатом
          schema:
            "$ref": "#/definitions/BanksList"
      deprecated: false

  /payout/v1/payouts:
    post:
      tags:
        - api-controller
      summary: Проведение выплаты
      operationId: payoutUsingPOST_1
      consumes:
        - application/json;charset=UTF-8
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: header
          name: Authorization
          description: Bearer secret key
          required: true
        - in: body
          name: Payout
          schema:
            "$ref": "#/definitions/Payout"
      responses:
        "200":
          description: Ответ с успешным результатом
          schema:
            "$ref": "#/definitions/PayoutRes"
      deprecated: false

  /payout/v1/payouts/{id}:
    get:
      tags:
        - api-controller
      summary: Получение информации по платежу
      operationId: getPayoutInfoUsingGET
      produces:
        - application/json;charset=UTF-8
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Bearer secret key
          required: true
        - name: Id
          in: path
          description: Id
          required: true
          type: string
      responses:
        '200':
          description: Ответ с успешным результатом
          schema:
            "$ref": "#/definitions/PayoutRes"
      deprecated: false

  <URL обработчика уведомлений на стороне партнёра>:
    post:
      tags:
        - Callback
      summary: Уведомление о статусе платежа
      operationId: sendCallback
      consumes:
        - application/json;charset=UTF-8
      parameters:
        - name: x-api-signature-sha256
          in: header
          description: SecretKey HMAC-SHA-256 (amount|id|statusValue|statusDate)
          required: true
        - name: Callback
          in: body
          schema:
            "$ref": "#/definitions/Callback"
      responses:
        200:
          description: Ответ с успешным результатом
          schema:
            "$ref": "#/definitions/EmptyBody"
      deprecated: false
definitions:
  Payout:
    type: object
    properties:
      id:
        type: string
        description: Aa-Zz0-9_-
        maxLength: 20
        example: 1404fhr7i272a2
      account:
        type: string
        description: Cчет для выплаты
        example: 40700000000000000000
      amount:
        type: number
        description: Сумма в рублях
        example: 1110.01
      currency:
        type: string
        description: Валюта платежа
        enum:
          - RUB
        maxLength: 3
        example: RUB
      paymentDetails:
        type: string
        description: Назначение платежа
        example: Выплата от страховой компании
      payoutMethod:
        enum:
          - SBP
        description: Тип выплаты
        example: SBP
      payoutParams:
        type: object
        properties:
          phone:
            type: string
            description: Номер телефона получателя
            example: '79191234567'
          bankAlias:
            type: string
            description: Код банка получателя из запроса списка банков
            example: 'RAIFFEISEN'
      incomeTypeCode:
        type: string
        enum:
          - "1"
          - "2"
          - "3"
        description: Код вида дохода<br/>[Значения описаны тут](http://www.consultant.ru/document/cons_doc_LAW_353568/527cf8edd2262cb7068cafd44ed596d9a05dd237/)
      extra:
        type: object
        description: Дополнительные данные
        properties:
          contract:
            type: string
            description: Номер договора для выплат
            example: '1234567/89012'
    title: Payout
  PayoutRes:
    type: object
    discriminator:
      mapping:

  BanksList:
    type: array
    items:
      "$ref": "#/definitions/Banks"
    properties:
      alias:
        type: string
        description: Алиас банка
        example: 'RAIFFEISEN'
    title: BanksList
  Banks:
    type: object
    properties:
      alias:
        type: string
        description: Алиас банка
        example: 'RAIFFEISEN'
      name:
        type: string
        description: Название банка
        example: 'Райффайзенбанк'
  Callback:
    type: object
    properties:
      event:
        type: string
        description: Тип операции
        example: 'payout'
      payout:
        type: object
        properties:
          id:
            type: string
            description: Aa-Zz0-9_-
            maxLength: 20
            example: 1404fhr7i272a2
          account:
            type: string
            description: Cчет для выплаты
            example: 40700000000000000000
          amount:
            type: number
            description: Сумма в рублях
            example: 1110.01
          currency:
            type: string
            description: Валюта платежа
            enum:
              - RUB
            maxLength: 3
            example: RUB
          payoutMethod:
            enum:
              - SBP
            description: Тип выплаты
            example: SBP
          payoutParams:
            type: object
            properties:
              phone:
                type: string
                description: Номер телефона получателя
                example: '79191234567'
              bankAlias:
                type: string
                description: Код банка получателя из запроса списка банков
                example: 'RAIFFEISEN'
          incomeTypeCode:
            type: string
            enum:
              - "1"
              - "2"
              - "3"
            description: Код вида дохода<br/>[Значения описаны тут](http://www.consultant.ru/document/cons_doc_LAW_353568/527cf8edd2262cb7068cafd44ed596d9a05dd237/)
          extra:
            type: object
            description: Дополнительные данные
            properties:
              contract:
                type: string
                description: Номер договора для выплат
                example: '1234567/89012'
          status:
            type: object
            properties:
              value:
                enum:
                  - IN_PROGRESS
                  - COMPLETED
                  - DECLINED
                description: Статус
                example: 'COMPLETED'
              date:
                description: Дата
                example: '2019-07-11T17:45:13+03:00'
          createDate:
            description: Дата создания
            example: '2019-07-11T17:45:13+03:00'
    title: Callback
  EmptyBody:
    type: object
  COMPLETED:
    type: object
    allOf:
      - $ref: "#/definitions/PayoutRes"
    properties:
      id:
        type: string
        description: Aa-Zz0-9_-
        example: 1404fhr7i272a2
      account:
        type: string
        description: Cчет для выплаты
        example: 40700000000000000000
      amount:
        type: number
        description: Сумма в рублях
        example: 1110.01
      currency:
        type: string
        description: Валюта платежа
        enum:
          - RUB
        maxLength: 3
        example: RUB
      payoutMethod:
        enum:
          - SBP
        description: Тип выплаты
        example: SBP
      payoutParams:
        type: object
        properties:
          phone:
            type: string
            description: Номер телефона получателя
            example: '79191234567'
          bankAlias:
            type: string
            description: Код банка получателя из запроса списка банков
            example: 'RAIFFEISEN'
      incomeTypeCode:
        type: string
        enum:
          - "1"
          - "2"
          - "3"
        description: Код вида дохода<br/>[Значения описаны тут](http://www.consultant.ru/document/cons_doc_LAW_353568/527cf8edd2262cb7068cafd44ed596d9a05dd237/)
      extra:
        type: object
        description: Дополнительные данные
        properties:
          contract:
            type: string
            description: Номер договора для выплат
            example: '1234567/89012'
      status:
        type: object
        properties:
          value:
            enum:
              - IN_PROGRESS
              - COMPLETED
              - DECLINED
            description: Статус
            example: 'COMPLETED'
          date:
            description: Дата
            example: '2019-07-11T17:45:13+03:00'
      createDate:
        description: Дата создания
        example: '2019-07-11T17:45:13+03:00'
    title: PayoutRes
  DECLINED:
    type: object
    allOf:
      - $ref: "#/definitions/PayoutRes"
    properties:
      id:
        type: string
        description: Aa-Zz0-9_-
        maxLength: 20
        example: 1404fhr7i272a2
      account:
        type: string
        description: Cчет для выплаты
        example: 40700000000000000000
      amount:
        type: number
        description: Сумма в рублях
        example: 1110.01
      currency:
        type: string
        description: Валюта платежа
        enum:
          - RUB
        maxLength: 3
        example: RUB
      payoutMethod:
        enum:
          - SBP
        description: Тип выплаты
        example: SBP
      payoutParams:
        type: object
        properties:
          phone:
            type: string
            description: Номер телефона получателя
            example: '79191234567'
          bankAlias:
            type: string
            description: Код банка получателя из запроса списка банков
            example: 'RAIFFEISEN'
      incomeTypeCode:
        type: string
        enum:
          - "1"
          - "2"
          - "3"
        description: Код вида дохода<br/>[Значения описаны тут](http://www.consultant.ru/document/cons_doc_LAW_353568/527cf8edd2262cb7068cafd44ed596d9a05dd237/)
      extra:
        type: object
        description: Дополнительные данные
        properties:
          contract:
            type: string
            description: Номер договора для выплат
            example: '1234567/89012'
      status:
        type: object
        properties:
          value:
            enum:
              - IN_PROGRESS
              - COMPLETED
              - DECLINED
            description: Статус
            example: 'DECLINED'
          declineReason:
            enum:
              - TIMEOUT
              - BANK_NOT_SUPPORTED
              - RECEIVER_ACCOUNT_ERROR
              - SYSTEM_ERROR
            description: Причина отклонения операции
            example: RECEIVER_ACCOUNT_ERROR
          date:
            description: Дата
            example: '2019-07-11T17:45:13+03:00'
      createDate:
        description: Дата создания
        example: '2019-07-11T17:45:13+03:00'
    title: PayoutRes
