---
swagger: '2.0'
info:
  title: Готовые решения партнеров по СБП
  contact: {
    email: ecom@raiffeisen.ru,
    name: Support e-mail
  }
  x-logo:
    url: images/raifflogo.png
    backgroundColor: '#FFFFFF'
    altText: Raiff logo
  description: |

    # Оффлайн

    ## Set Retail от CSI

    https://www.crystals.ru/

    Под кассы с решением Set Retail уже есть готовый модуль с СБП.
    Для уточнения условий установки и настройки можете обратится к вашему менеджеру в CSI.
    Модуль позволяет генерировать QR как на дополнительных экранах так и на предчеках.

    ## Бифит

    https://kassa.bifit.com/

    Кассовое ПО и оборудование для сервисов доставки,
    транспортных компаний, розничной торговли
    и общественного питания

    Бифит поддерживает прием платежей через СБП в мобильных кассах в соответствии с 54-ФЗ.
    Для наших клиентов тарифы на обслуживание кассы дешевле. Скидка от 40% до 70%

    Касса Розница
    Рабочее место кассира
    и кабинет управления розничной торговой точкой

    Касса Курьер
    Приложение для курьеров, личный кабинет диспетчера
    и приложение для точки продаж и самовывоза

    Касса Транспорт
    Приложение для водителя, кабинет управления автопарком и облачная касс

    Касса Общепит
    Кассовое приложение
    и система учета для предприятий питания

    Оборудование:
    * Смарт-касса А930
    * Смарт-касса MSPOS-Е-Ф
    * Смарт-касса Limon Smart Bank

    ## Life Pay

    https://life-pay.ru/

    Терминалы и кассы.
    Подхоядят для курьеров, торговли и общепитов.

    ## Paykeeper

    https://paykeeper.ru/

    PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
    специализируется на интернет-эквайринге

    Техническая поддержка «под ключ»:
    * Подключит сайт к приему платежей на любой CMS
    * Приведет сайт в соответствие с требованиями банка
    * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
    * Предоставит ЛК для управления платежами
    * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
    * Поможет решить технические вопросы

    Тарифы за поддержку:
    * Первые 6 месяцев –– бесплатно
    * После 6 месяцев –– 5 900 ₽/год
    * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

    Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

    ## Direct Vision

    http://www.directvision.ru/

    Полный цикл автоматизации АЗС включает всё необходимое программное обеспечение и пуско-наладочные работы.
    Так же имеет готовый модуль с приемом оплаты по СБП.

    ## Iiko

    https://iiko.ru/

    Система автоматизации ресторанов.

    # Онлайн

    ## MODX

    https://paykeeper.ru/

    PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
    специализируется на интернет-эквайринге

    Техническая поддержка «под ключ»:
    * Подключит сайт к приему платежей на любой CMS
    * Приведет сайт в соответствие с требованиями банка
    * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
    * Предоставит ЛК для управления платежами
    * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
    * Поможет решить технические вопросы

    Тарифы за поддержку:
    * Первые 6 месяцев –– бесплатно
    * После 6 месяцев –– 5 900 ₽/год
    * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

    Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

    ## 1c-Bitrix

    https://paykeeper.ru/

    PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
    специализируется на интернет-эквайринге

    Техническая поддержка «под ключ»:
    * Подключит сайт к приему платежей на любой CMS
    * Приведет сайт в соответствие с требованиями банка
    * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
    * Предоставит ЛК для управления платежами
    * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
    * Поможет решить технические вопросы

    Тарифы за поддержку:
    * Первые 6 месяцев –– бесплатно
    * После 6 месяцев –– 5 900 ₽/год
    * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

    Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

    ## UMI.CMS

    https://paykeeper.ru/

    PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
    специализируется на интернет-эквайринге

    Техническая поддержка «под ключ»:
    * Подключит сайт к приему платежей на любой CMS
    * Приведет сайт в соответствие с требованиями банка
    * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
    * Предоставит ЛК для управления платежами
    * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
    * Поможет решить технические вопросы

    Тарифы за поддержку:
    * Первые 6 месяцев –– бесплатно
    * После 6 месяцев –– 5 900 ₽/год
    * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

    Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

    ## Joomla

    https://paykeeper.ru/

    PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
    специализируется на интернет-эквайринге

    Техническая поддержка «под ключ»:
    * Подключит сайт к приему платежей на любой CMS
    * Приведет сайт в соответствие с требованиями банка
    * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
    * Предоставит ЛК для управления платежами
    * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
    * Поможет решить технические вопросы

    Тарифы за поддержку:
    * Первые 6 месяцев –– бесплатно
    * После 6 месяцев –– 5 900 ₽/год
    * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

    Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

    ## Opencart

    https://paykeeper.ru/

    PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
    специализируется на интернет-эквайринге

    Техническая поддержка «под ключ»:
    * Подключит сайт к приему платежей на любой CMS
    * Приведет сайт в соответствие с требованиями банка
    * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
    * Предоставит ЛК для управления платежами
    * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
    * Поможет решить технические вопросы

    Тарифы за поддержку:
    * Первые 6 месяцев –– бесплатно
    * После 6 месяцев –– 5 900 ₽/год
    * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

    Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

    ## WordPress

    https://paykeeper.ru/

    PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
    специализируется на интернет-эквайринге

    Техническая поддержка «под ключ»:
    * Подключит сайт к приему платежей на CMS
    * Приведет сайт в соответствие с требованиями банка
    * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
    * Предоставит ЛК для управления платежами
    * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
    * Поможет решить технические вопросы

    Тарифы за поддержку:
    * Первые 6 месяцев –– бесплатно
    * После 6 месяцев –– 5 900 ₽/год
    * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

    Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно
