---
swagger: '2.0'
info:
  title: Готовые решения
  contact: {
    email: ecom@raiffeisen.ru,
    name: Support e-mail
  }
  x-logo:
    url: images/raifflogo.png
    backgroundColor: '#FFFFFF'
    altText: Raiff logo
    description: |

tags:
  - name: setretail
    x-displayName: Set Retail от CSI
    description: |
     <a href='images/logocsi.png' target='_blank'><img src='images/logocsi.png'></a>

     **Сайт:**

     https://www.crystals.ru/

     **Сфера деятельности:**

     Ритейл

     **Описание:**

     Разрабатывают программы для розничной торговли — Set Retail и Set Prisma установлены в тысячах магазинов по всей стране.
     Создают и производят кассовые решения, поставляют торговое оборудование лучших мировых компаний.
     Помогают магазинам развиваться и привлекать новых покупателей.
     Под кассы с решением Set Retail уже есть готовый модуль с СБП.
     Для уточнения условий установки и настройке можете обратиться к вашему менеджеру в CSI.
     Модуль позволяет генерировать QR как на дополнительных экранах так и на предчеках.

     **Инструкция:**

     Инструкция по настройке ПО: https://crystals.atlassian.net/wiki/spaces/SR10SUPPORT/pages/1810141803/QR-+Raiffeisen

  - name: artix
    x-displayName: Artix
    description: |
     <a href='images/logoartix.png' target='_blank'><img src='images/logoartix.png'></a>

     **Сайт:**

     http://artix.su/

     **Сфера деятельности:**

     Ритейл

     **Описание:**

     Artix - это компания, предоставляющая комплекс решений по автоматизации вашего бизнеса: современного программного обеспечения и различного торгового оборудования.

     Опыт интеграции любого масштаба Федеральная сеть с 3000 касс или магазин с 3 кассами — мы используем опыт крупных внедрений на малых предприятиях.

     Поддержка широкого спектра оборудования: ПО работает на оборудовании различных производителей, клиент сам решает какую модель использовать.

     Низкие системные требования продукты работают на минимальных конфигурациях, что позволяет сэкономить на модернизации оборудования.

     **Инструкция:**

     Инструкция по настройке ПО: http://docs.artix.su/pages/viewpage.action?pageId=42827865

  - name: bifit
    x-displayName: Бифит
    description: |
     <a href='images/logobifit.png' target='_blank'><img src='images/logobifit.png'></a>

     **Сайт:**

     [https://kassa.bifit.com/](https://kassa.bifit.com/partnerlead/)

     **Сфера деятельности:**

     Любые направления

     **Описание:**

     Кассовое ПО и оборудование для сервисов доставки,
     транспортных компаний, розничной торговли
     и общественного питания.

     Бифит поддерживает прием платежей через СБП в мобильных кассах в соответствии с 54-ФЗ.
     Для наших клиентов тарифы на обслуживание кассы дешевле. Скидка от 40% до 70%

     Касса Розница
     Рабочее место кассира
     и кабинет управления розничной торговой точкой

     Касса Курьер
     Приложение для курьеров, личный кабинет диспетчера
     и приложение для точки продаж и самовывоза

     Касса Транспорт
     Приложение для водителя, кабинет управления автопарком и облачная касс

     Касса Общепит
     Кассовое приложение
     и система учета для предприятий питания

     Оборудование:
     * Смарт-касса А930
     * Смарт-касса MSPOS-Е-Ф
     * Смарт-касса Limon Smart Bank

     **Инструкция:**

     Инструкция по настройке ПО: [Инструкция в формате PDF](images/instructionBifit.pdf)

  - name: lifepay
    x-displayName: Life Pay
    description: |
     <a href='images/logolifepay.png' target='_blank'><img src='images/logolifepay.png'></a>

     **Сайт:**

     [https://life-pay.ru/](https://life-pay.ru/partners/?partner_id=46839)

     **Сфера деятельности:**

     Розничная торговля, сфера услуг, доставка и логистика

     **Описание:**

     Технологичные POS-решения для компаний и корпораций

     ●	Приложение LIFE POS для малого бизнеса. Фискализация и прием платежей любыми удобными способами: по картам, Apple Pay, Google Pay, Samsung Pay, по QR-коду через Систему быстрых платежей.

     ●	Приложение LIFE POS Checkout, которое может интегрироваться с учетными системами и курьерскими приложениями через открытый API.

     ●	Приложение LIFE POS Delivery для доставки, которое позволяет отслеживать статус заказов, посылать актуальную информацию об адресах и контактах заказчика, а также принимать платежи мобильным сотрудникам.

     ●	mPOS-терминалы, SoftPOS-решения, POS-терминалы, фискальные регистраторы и смарт-терминалы.

     ●	Облачная фискализация для мобильных торговых точек, доставки и онлайн-продаж.

     **Инструкция:**

     Инструкция по настройке ПО: [Инструкция в формате PDF](images/instructionLifePay.pdf)

  - name: paykeeper
    x-displayName: Paykeeper
    description: |
     <a href='images/logopaykeeper.png' target='_blank'><img src='images/logopaykeeper.png'></a>

     **Сайт:**

     [https://paykeeper.ru](https://raiffeisen-processing.ru/)

     **Сфера деятельности:**

     Любые направления

     **Описание:**

     PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
     специализируется на интернет-эквайринге

     Техническая поддержка «под ключ»:
     * Подключит сайт к приему платежей на любой CMS
     * Приведет сайт в соответствие с требованиями банка
     * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
     * Предоставит ЛК для управления платежами
     * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
     * Поможет решить технические вопросы

     Тарифы за поддержку:
     * Первые 6 месяцев –– бесплатно
     * После 6 месяцев –– 5 900 ₽/год
     * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

     Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

     В данном случае для ритейла предлагается использовать личный кабинет paykeeper который можно открыть на смартфонах, планшетах или ПК и там генерироваться QR, видеть статус оплаты, проводить возвраты. Так же можно настроить фискализацию.
     Нюансом является отсутствие интеграции с учетными системами в рознице.

     **Инструкция:**

     Пример личного кабинета: https://test-raiffeisen.server.paykeeper.ru/payments/payments  Логин: demo  Пароль: 123

  - name: directvision
    x-displayName: Direct Vision
    description: |
     <a href='images/logodirectvision.png' target='_blank'><img src='images/logodirectvision.png'></a>

     **Сайт:**

     http://www.directvision.ru/

     **Сфера деятельности:**

     АЗС, Кафе на АЗС, Магазин на АЗС

     **Описание:**

     Полный цикл автоматизации АЗС включает всё необходимое программное обеспечение и пуско-наладочные работы.
     Так же имеет готовый модуль с приемом оплаты по СБП.

  - name: iiko
    x-displayName: Iiko
    description: |
     <a href='images/logoiiko.png' target='_blank'><img src='images/logoiiko.png'></a>

     **Сайт:**

     https://iiko.ru/

     **Сфера деятельности:**

     Ресторан, Кафе, Столовая, Кофейня, Фудтрак

     **Описание:**

     iiko – единая система для управления продажами, складом, кухней, доставкой, персоналом, финансами, поставщиками, лояльностью гостей – всеми процессами в ресторане.
     Поскольку все данные обрабатываются в единой системе, информация о выручке, себестоимости, остатках на складах, а также финансовые отчеты и все действия сотрудников видны в реальном времени.
     Система автоматизации ресторанов.

     **Инструкция:**

     Инструкция по подключению и настройке СБП: https://ru.iiko.help/articles/#!special-iiko/reiffeisen-sbp

  - name: Invoice
    x-displayName: Invoice
    description: |
     <a href='images/logoinvoice.png' target='_blank'><img src='images/logoinvoice.png'></a>

     **Сайт:**

     [https://invoice.su/](https://raiffeisen.invoice.su/)

     **Сфера деятельности:**

     Любые направления

     **Описание:**

     Настроит оплату в мессенджере Telegram для ваших сотрудников. Создаст защищенные чаты для каждой торговой точки, чтобы кассиры со своих смартфонов создавали QR-коды, показывали покупателям и проверяли статусы оплат

     Подключит к программе лояльности, чтобы ваши клиенты могли получать бонусные баллы при оплате по QR-кодам у вас и в других точках

     **Инструкция:**

     https://invoice.su/integration

  - name: joinposter
    x-displayName: Joinposter
    description: |
     <a href='images/logoinvoice.png' target='_blank'><img src='images/logoinvoice.png'></a>

     **Сайт:**

     [https://joinposter.com](https://joinposter.com)

     **Сфера деятельности:**

     Ресторан, Кафе, Столовая, Кофейня, Фудтрак

     **Описание:**

     Технологический партнер Райффайзенбанк компания Invoice реализовала интеграцию с Joinposter для всех клиентов Райффайзенбанк.

     Joinposter – это облачная программа, включающая в себя функционал программного обеспечения для онлайн-кассы согласно 54-ФЗ,  товарного и складского учета, приема заказов, аналитики, управления продажами и маркетинга

     **Инструкция:**

     1. Открыть счет в Райффайзенбанк

     2. Оставить заявку на подключение к сервису на лендинге партнера https://raiffeisen.invoice.su/

     3. Установить модуль https://joinposter.com/applications/invoice

  - name: 1cbitrix
    x-displayName: 1c-Bitrix
    description: |
     <a href='images/logo1bitrix.png' target='_blank'><img src='images/logo1bitrix.png'></a><a href='images/logopaykeeper.png' target='_blank'><img src='images/logopaykeeper.png'></a>

     **Инструкция:**

     https://docs.paykeeper.ru/cms/bitrix/

     **Решения:**

     СБП и Интернет эквайринг

     **Партнер:**

     https://raiffeisen-processing.ru/

     PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
     специализируется на интернет-эквайринге

     Техническая поддержка «под ключ»:
     * Подключит сайт к приему платежей на любой CMS
     * Приведет сайт в соответствие с требованиями банка
     * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
     * Предоставит ЛК для управления платежами
     * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
     * Поможет решить технические вопросы

     Тарифы за поддержку:
     * Первые 6 месяцев –– бесплатно
     * После 6 месяцев –– 5 900 ₽/год
     * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

     Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

  - name: wordpress
    x-displayName: WordPress
    description: |
     <a href='images/logowordpress.png' target='_blank'><img src='images/logowordpress.png'></a> <a href='images/logopaykeeper.png' target='_blank'><img src='images/logopaykeeper.png'></a>

     **Инструкция:**

     https://docs.paykeeper.ru/cms/modul-oplaty-dlya-woocommerce/

     **Решения:**

     СБП и Интернет эквайринг

     **Партнер:**

     https://raiffeisen-processing.ru/

     PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
     специализируется на интернет-эквайринге

     Техническая поддержка «под ключ»:
     * Подключит сайт к приему платежей на CMS
     * Приведет сайт в соответствие с требованиями банка
     * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
     * Предоставит ЛК для управления платежами
     * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
     * Поможет решить технические вопросы

     Тарифы за поддержку:
     * Первые 6 месяцев –– бесплатно
     * После 6 месяцев –– 5 900 ₽/год
     * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

     Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

  - name: opencart
    x-displayName: Opencart
    description: |
     <a href='images/logoopencart.png' target='_blank'><img src='images/logoopencart.png'></a> <a href='images/logopaykeeper.png' target='_blank'><img src='images/logopaykeeper.png'></a>

     **Инструкция:**

     https://docs.paykeeper.ru/cms/opencart/

     **Решения:**

     СБП и Интернет эквайринг

     **Партнер:**

     https://raiffeisen-processing.ru/

     PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
     специализируется на интернет-эквайринге

     Техническая поддержка «под ключ»:
     * Подключит сайт к приему платежей на любой CMS
     * Приведет сайт в соответствие с требованиями банка
     * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
     * Предоставит ЛК для управления платежами
     * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
     * Поможет решить технические вопросы

     Тарифы за поддержку:
     * Первые 6 месяцев –– бесплатно
     * После 6 месяцев –– 5 900 ₽/год
     * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

     Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

  - name: umi
    x-displayName: UMI.CMS
    description: |
     <a href='images/logoumicms.png' target='_blank'><img src='images/logoumicms.png'></a> <a href='images/logopaykeeper.png' target='_blank'><img src='images/logopaykeeper.png'></a>

     **Инструкция:**

     https://docs.paykeeper.ru/cms/umi-cms/

     **Решения:**

     СБП и Интернет эквайринг

     **Партнер:**

     https://raiffeisen-processing.ru/

     PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
     специализируется на интернет-эквайринге

     Техническая поддержка «под ключ»:
     * Подключит сайт к приему платежей на любой CMS
     * Приведет сайт в соответствие с требованиями банка
     * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
     * Предоставит ЛК для управления платежами
     * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
     * Поможет решить технические вопросы

     Тарифы за поддержку:
     * Первые 6 месяцев –– бесплатно
     * После 6 месяцев –– 5 900 ₽/год
     * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

     Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

  - name: joomla
    x-displayName: Joomla
    description: |
     <a href='images/logojoomla.png' target='_blank'><img src='images/logojoomla.png'></a> <a href='images/logopaykeeper.png' target='_blank'><img src='images/logopaykeeper.png'></a>

     **Инструкция:**

     https://docs.paykeeper.ru/cms/joomla/

     **Решения:**

     СБП и Интернет эквайринг

     **Партнер:**

     https://raiffeisen-processing.ru/

     PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
     специализируется на интернет-эквайринге

     Техническая поддержка «под ключ»:
     * Подключит сайт к приему платежей на любой CMS
     * Приведет сайт в соответствие с требованиями банка
     * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
     * Предоставит ЛК для управления платежами
     * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
     * Поможет решить технические вопросы

     Тарифы за поддержку:
     * Первые 6 месяцев –– бесплатно
     * После 6 месяцев –– 5 900 ₽/год
     * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

     Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

  - name: modx
    x-displayName: MODX
    description: |
     <a href='images/logomodx.png' target='_blank'><img src='images/logomodx.png'></a> <a href='images/logopaykeeper.png' target='_blank'><img src='images/logopaykeeper.png'></a>

     **Инструкция:**

     https://docs.paykeeper.ru/cms/modul-oplaty-dlya-shopkeeper/

     **Решения:**

     СБП и Интернет эквайринг

     **Партнер:**

     https://raiffeisen-processing.ru/

     PayKeeper — один из крупнейших российских интеграторов, партнер Райффайзенбанка
     специализируется на интернет-эквайринге

     Техническая поддержка «под ключ»:
     * Подключит сайт к приему платежей на любой CMS
     * Приведет сайт в соответствие с требованиями банка
     * Настроит стационарную или облачную кассу в соответствии с 54-ФЗ
     * Предоставит ЛК для управления платежами
     * Оплата по ссылке (легкий платеж), создание QR-кодов, отмена операций, возвраты
     * Поможет решить технические вопросы

     Тарифы за поддержку:
     * Первые 6 месяцев –– бесплатно
     * После 6 месяцев –– 5 900 ₽/год
     * При обороте менее 50 000 ₽/мес тариф — 2 950 ₽/год

     Спустя 6 месяцев клиент может отказаться от услуг PayKeeper и осуществлять поддержку самостоятельно

  - name: sbp
    x-displayName: СБП
    description: |
     * [Java](https://github.com/Raiffeisen-DGTL/sbp-sdk-java)

  - name: ecom
    x-displayName: ECOM
    description: |
     * [JavaScript](https://github.com/Raiffeisen-DGTL/ecom-sdk-javascript)

x-tagGroups:
  - name: Оффлайн (СБП)
    tags:
      - setretail
      - artix
      - bifit
      - lifepay
      - paykeeper
      - directvision
      - iiko
      - Invoice
      - joinposter
  - name: Онлайн (ECOM и СБП)
    tags:
      - 1cbitrix
      - wordpress
      - opencart
      - umi
      - joomla
      - modx
  - name: SDK
    tags:
      - sbp
      - ecom
